### ISSUE TITLE
AttributeError: module 'settings' has no attribute 'MASHAPE_API_KEY'

### ISSUE THREAD

**Issue by mnishig** [aquatix/digimarks#18]
I installed  digimarks with README.rst instruction. 
but, when I bookmark add, following Error occured at brower screen and log .

```
127.0.0.1 - - [28/Apr/2020 10:01:02] "POST /0b239ff2044ef51995db310acdba97a36973af73616cf424/adding HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/opt/ws/digimarks/p3/lib/python3.7/site-packages/flask/app.py", line 2463, in __call__
    return self.wsgi_app(environ, start_response)
  File "/opt/ws/digimarks/p3/lib/python3.7/site-packages/flask/app.py", line 2449, in wsgi_app
    response = self.handle_exception(e)
  File "/opt/ws/digimarks/p3/lib/python3.7/site-packages/flask/app.py", line 1866, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/opt/ws/digimarks/p3/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/opt/ws/digimarks/p3/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/ws/digimarks/p3/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/opt/ws/digimarks/p3/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/opt/ws/digimarks/p3/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/opt/ws/digimarks/p3/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/ws/digimarks/p3/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/ws/digimarks/digimarks.py", line 781, in addingbookmark
    bookmark = updatebookmark(userkey)
  File "/opt/ws/digimarks/digimarks.py", line 765, in updatebookmark
    bookmark.set_favicon()
  File "/opt/ws/digimarks/digimarks.py", line 412, in set_favicon
    self._set_favicon_with_realfavicongenerator(domain)
  File "/opt/ws/digimarks/digimarks.py", line 362, in _set_favicon_with_realfavicongenerator
    headers={'User-Agent': DIGIMARKS_USER_AGENT, 'X-Mashape-Key': settings.MASHAPE_API_KEY}
AttributeError: module 'settings' has no attribute 'MASHAPE_API_KEY'
```

and I add MASHAPE_API_KEY at settings.py like this

`MASHAPE_API_KEY = '[MY-SECRET-API-KEY]'`

Digimarks looks like run normaly.
My suggestion, description of MASHAPE_API_KEY add to README.rst

**Comment by aquatix** [comment]
Thanks! That is a nice oversight from the example settings.py indeed. I commented on the PR.

This key is used for requesting favicons for the websites that are being bookmarked by the way.
